name: Workflow with Output Reference

on:
  push:
    branches:
      - main

jobs:
  set_output_job:
    runs-on: ubuntu-latest
    steps:
      - name: Set Random Output
        id: set_output
        run: |
          # Generate a random string using openssl
          random_string=$(openssl rand -hex 16)
          echo "RandomString=$random_string" >> $GITHUB_ENV

  use_output_job:
    needs: set_output_job
    runs-on: ubuntu-latest
    steps:
      - name: Use Output
        run: |
          # Access the output from the "Set Random Output" job
          echo "The random output is $RandomString"
