name: dynamic

on:
  push:
  workflow_dispatch:

jobs:
  set_output_job:
    runs-on: ubuntu-latest
    outputs:
      random-output: ${{ steps.set_output.outputs.random-output }}
    steps:
      - name: Set Random Output
        id: set_output
        run: |
          # Generate a random string using openssl
          random_string=$(openssl rand -hex 16)
          echo "::set-output name=random-output::$random_string"
          echo $random_string > random_output.txt

  use_output_job:
    needs: set_output_job
    runs-on: ubuntu-latest
    steps:
      - name: Use Output
        env:
          RANDOM_OUTPUT: ${{ needs.set_output_job.outputs.random-output }}
        run: |
          # Read the random output from the environment variable
          random_string=$RANDOM_OUTPUT
          echo "The random output is $random_string"
