on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        default: "Dev-SPM"
        type: choice
        options:
          - Dev-SPM
          - Dev2-SPM
          - Dev3-SPM
          - Devmaster-SPM
          - Test-Spm1
          - Test-Spm2
          - Test3-SPM
          - Test4-SPM

jobs:
  run-test-and-upload-results:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash --noprofile --norc -e -o pipefail {0}
    container:
      image: 'image.services.polcloud.org/image/nbit-tests:1.0.0-FINAL'
      volumes:
        - /var/run/secrets/eks.amazonaws.com/serviceaccount/token:/var/run/secrets/eks.amazonaws.com/serviceaccount/token

    steps:
      - name: Set Environment Value
        id: set-environment
        run: |
          if [[ "${{ inputs.environment }}" == 'Dev-SPM' ]]; then
            echo "ENVIRONMENT_VALUE=588494385378" >> $GITHUB_ENV
            echo "set-environment.result=success" >> $GITHUB_ENV
          elif [[ "${{ inputs.environment }}" == 'Dev2-SPM' ]]; then
            echo "ENVIRONMENT_VALUE=445892920784" >> $GITHUB_ENV
            echo "set-environment.result=success" >> $GITHUB_ENV
          # ... rest of the conditions ...
          else
            echo "ENVIRONMENT_VALUE=" >> $GITHUB_ENV
            echo "set-environment.result=failure" >> $GITHUB_ENV
          fi

      - name: Display Environment Value
        run: |
          echo "ENVIRONMENT_VALUE=$ENVIRONMENT_VALUE"

      - name: Check Result
        run: |
          echo "set-environment.result=${{ env['set-environment.result'] }}"

