name: Job 2

on:
  workflow_dispatch:

jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Job 1
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: yamini9091/githubactions
          workflow: job1.yml
          ref: main

      - name: Wait for Job 1 to complete
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log("Waiting for Job 1 to complete...");
            const { data: workflowRuns } = await octokit.rest.actions.listWorkflowRuns({
              owner: 'yamini9091',
              repo: 'githubactions,
              workflow_file_name: 'job1.yml',
              event: 'repository_dispatch'
            });
            const job1RunId = workflowRuns.workflow_runs[0].id;
            console.log(`Job 1 workflow run ID: ${job1RunId}`);
            while (true) {
              const { data: workflowRun } = await octokit.rest.actions.getWorkflowRun({
                owner: 'yamini9091',
                repo: 'githubactions',
                run_id: job1RunId
              });
              if (workflowRun.status === 'completed') {
                console.log(`Job 1 completed with status: ${workflowRun.conclusion}`);
                break;
              }
              console.log(`Job 1 status: ${workflowRun.status}`);
              await new Promise(resolve => setTimeout(resolve, 5000)); // Wait for 5 seconds before checking again
            }

      - name: Continue with Job 2
        run: |
          # Add your Job 2 steps here
