name: Workflow with Output Reference

on:
  push:
  workflow_dispatch:

jobs:
  set_output_job:
    runs-on: ubuntu-latest
    steps:
      - name: Set Random Output
        id: set_output
        run: |
          # Generate a random string using openssl
          random_string=$(openssl rand -hex 16)
          echo "::set-output name=random-output::$random_string"

  use_output_job:
    needs: set_output_job
    runs-on: ubuntu-latest
    steps:
      - name: Use Output
        run: |
          # Access the random output directly from the previous job's outputs
          random_string=${{ needs.set_output_job.outputs.random-output }}
          echo "The random output is $random_string"
