# Repo B - main.yml
name: Workflow

on:
  push:
    branches:
      - main

jobs:
  job-a:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use Job Template from Repo A
        uses: yamini9091/githubactions/.github/workflows/job-template.yml@main

      - name: Retrieve Output from Job Template
        run: echo "The output from the Job Template is ${{ needs.template-job.outputs.my-output }}"

  job-b:
    needs: job-a
    runs-on: ubuntu-latest
    steps:
      - name: Run Second Job
        run: echo "The output from Job A is ${{ needs.job-a.outputs.my-output }}"
