# .github/workflows/main.yml

name: Main Workflow

on:
 push:

jobs:
  test_job:
    name: Test Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your desired steps here

      - name: Run tests
        run: echo "Running tests..."

      - name: Set output
        id: set_output
        run: |
          echo "::set-output name=output_value1::1"
          echo "::set-output name=output_value2::2"

  reference_template_job:
    needs: test_job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your desired steps here

      - name: Use output from test_job
        run: echo "Output from test_job:${{ needs.test_job.outputs.output_value1 }}"
