name: Reusable workflow

on:
 push:
 workflow_dispatch:

jobs:
 job1:
   uses: ./.github/workflows/joboutput.yml
   
 job2:
  runs-on: ubuntu-latest
  needs: job1
  steps: 
  - run: |
       echo "Output from job1-template - output1: ${{ needs.job1.job1-template.outputs.output1 }}, output2: ${{ needs.job1.job1-template.outputs.output2 }}"
  
 
