name: Reusable workflow

on:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Run joboutput.yml
        id: job1-template
        uses: ./.github/workflows/joboutput.yml

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Print job1-template outputs
        run: |
          echo "Output from job1-template - output1: ${{ needs.job1.outputs.output1 }}, output2: ${{ needs.job1.outputs.output2 }}"
